### ISSUE TITLE
Roadmap 1.0.0

### ISSUE THREAD

**Issue by disizali** [irandeno/coffee#1]
todo list in the way to 1.0.0 : 
- [x] custom environment variables
- [x] support .json 
- [x] project structure
  - [x] config/[environment].js-json
  - [x] default configuration file
  - [x] ability to explicity specify config file
  - [x] auto detect environment for target configuration
- [x] make api available
  - [x] coffee.get
  - [x] coffee.has
  - [x] coffee.set
- [x] ci
  - [x] tests
- [x] error handling
- [x] documentaion
- [x] publish to deno.land/x and update example links

**Comment by Aslemammad** [comment]
For friends who read this comment, I'm working on .yml files, so please dont pay your attention on that.

**Comment by disizali** [comment]
[v1.0.0](https://github.com/irandeno/coffee/releases/tag/1.0.0) Released !
